const recipes = {
    "spaghetti": "Ingredients: Spaghetti, Tomatoes, Garlic, Olive Oil. Instructions: Boil spaghetti. Cook tomatoes with garlic. Combine and serve.",
    "tacos": "Ingredients: Tortillas, Beef, Lettuce, Cheese. Instructions: Cook beef. Fill tortillas with beef, lettuce, and cheese.",
    "pancakes": "Ingredients: Flour, Milk, Eggs, Sugar. Instructions: Mix ingredients. Cook on a skillet until golden.",
    "salad": "Ingredients: Lettuce, Tomato, Cucumber, Dressing. Instructions: Chop ingredients and mix with dressing.",
    "chicken curry": "Ingredients: Chicken, Curry Powder, Onion, Coconut Milk. Instructions: Sauté onions, add chicken, curry, and coconut milk. Simmer until cooked.",
    "fried rice": "Ingredients: Rice, Vegetables, Soy Sauce, Eggs. Instructions: Sauté vegetables, add rice and soy sauce, stir in eggs.",
    "omelette": "Ingredients: Eggs, Cheese, Bell Peppers, Salt. Instructions: Whisk eggs, pour into a pan, add cheese and peppers, cook until set.",
    "pizza": "Ingredients: Pizza Dough, Tomato Sauce, Cheese, Toppings. Instructions: Spread sauce on dough, add toppings, bake until golden.",
    "lasagna": "Ingredients: Lasagna Noodles, Ricotta, Marinara Sauce, Mozzarella. Instructions: Layer noodles, cheese, and sauce. Bake until bubbly.",
    "burger": "Ingredients: Ground Beef, Buns, Lettuce, Tomato. Instructions: Grill patties, assemble with buns and toppings.",
    "stir fry": "Ingredients: Vegetables, Soy Sauce, Chicken or Tofu, Rice. Instructions: Stir fry vegetables and protein, serve over rice.",
    "cookies": "Ingredients: Flour, Sugar, Butter, Chocolate Chips. Instructions: Mix ingredients, scoop onto a baking sheet, bake until golden.",
    "smoothie": "Ingredients: Banana, Spinach, Yogurt, Honey. Instructions: Blend all ingredients until smooth.",
    "butter chicken": "Ingredients: Chicken, Butter, Cream, Tomato Sauce. Instructions: Cook chicken in butter, add cream and sauce, simmer.",
    "beef stew": "Ingredients: Beef, Carrots, Potatoes, Broth. Instructions: Brown beef, add vegetables and broth, simmer until tender.",
    "margarita pizza": "Ingredients: Pizza Dough, Tomato Sauce, Fresh Basil, Mozzarella. Instructions: Spread sauce on dough, add cheese and basil, bake.",
    "vegetable stir fry": "Ingredients: Mixed Vegetables, Soy Sauce, Garlic, Ginger. Instructions: Sauté vegetables with garlic and ginger, add soy sauce.",
    "quiche": "Ingredients: Pie Crust, Eggs, Cream, Cheese, Vegetables. Instructions: Whisk eggs and cream, add cheese and vegetables, bake in crust.",
    "clams linguine": "Ingredients: Linguine, Clams, Garlic, White Wine. Instructions: Cook linguine, sauté garlic, add clams and wine, toss with pasta.",
    "butter chicken": "Ingredients: Chicken, Butter, Cream, Tomato Sauce, Spices. Instructions: Cook chicken in butter, add cream and tomato sauce, simmer with spices.",
    "biryani": "Ingredients: Basmati Rice, Chicken or Vegetables, Spices, Yogurt. Instructions: Layer marinated chicken or vegetables with rice, cook until done.",
    "paneer tikka": "Ingredients: Paneer, Yogurt, Spices, Bell Peppers. Instructions: Marinate paneer and peppers, skewer and grill until charred.",
    "dal makhani": "Ingredients: Black Lentils, Cream, Butter, Spices. Instructions: Cook lentils overnight, simmer with cream and spices.",
    "chole bhature": "Ingredients: Chickpeas, Flour, Spices, Yogurt. Instructions: Cook chickpeas with spices, serve with deep-fried bhature.",
    "samosa": "Ingredients: Potatoes, Peas, Spices, Flour. Instructions: Make a spiced potato filling, encase in dough, deep fry until golden.",
    "palak paneer": "Ingredients: Spinach, Paneer, Cream, Spices. Instructions: Cook spinach, blend, and simmer with paneer and cream.",
    "pav bhaji": "Ingredients: Mixed Vegetables, Pav, Spices, Butter. Instructions: Mash cooked vegetables with spices, serve with buttered pav.",
    "rasgulla": "Ingredients: Paneer, Sugar, Water. Instructions: Boil paneer, form balls, cook in sugar syrup until spongy.",
    "lasagna": "Ingredients: Lasagna Noodles, Ricotta, Marinara Sauce, Mozzarella. Instructions: Layer noodles, cheese, and sauce. Bake until bubbly.",
    "risotto": "Ingredients: Arborio Rice, Broth, Onion, Parmesan. Instructions: Sauté onions, add rice, gradually stir in broth until creamy.",
    "fettuccine alfredo": "Ingredients: Fettuccine, Butter, Cream, Parmesan. Instructions: Cook fettuccine, melt butter, add cream and cheese, toss with pasta.",
    "carbonara": "Ingredients: Spaghetti, Eggs, Pancetta, Pecorino Cheese. Instructions: Cook pasta, mix eggs with cheese, combine with hot pasta and pancetta.",
    "gnocchi": "Ingredients: Potatoes, Flour, Eggs. Instructions: Make a dough, form into small pieces, boil until they float.",
    "bruschetta": "Ingredients: Baguette, Tomatoes, Basil, Olive Oil. Instructions: Toast bread, top with chopped tomatoes and basil.",
    "caprese salad": "Ingredients: Tomatoes, Mozzarella, Basil, Olive Oil. Instructions: Layer tomatoes and mozzarella, drizzle with olive oil and sprinkle with basil.",
    "osso buco": "Ingredients: Veal Shanks, White Wine, Broth, Vegetables. Instructions: Brown shanks, braise with wine and broth until tender.",
    "tiramisu": "Ingredients: Mascarpone, Coffee, Ladyfingers, Cocoa. Instructions: Layer soaked ladyfingers with mascarpone mixture, dust with cocoa.",
    "burger": "Ingredients: Ground Beef, Buns, Lettuce, Tomato, Cheese. Instructions: Grill patties, assemble with toppings in buns.",
    "french fries": "Ingredients: Potatoes, Oil, Salt. Instructions: Cut potatoes, fry in oil until golden and crispy, season with salt.",
    "chicken nuggets": "Ingredients: Chicken Breast, Bread Crumbs, Egg, Spices. Instructions: Cut chicken, coat in egg and bread crumbs, fry until golden.",
    "hot dog": "Ingredients: Hot Dog Sausage, Buns, Mustard, Ketchup. Instructions: Grill sausages, serve in buns with toppings.",
    "pizza": "Ingredients: Pizza Dough, Tomato Sauce, Cheese, Toppings. Instructions: Spread sauce on dough, add cheese and toppings, bake.",
    "onion rings": "Ingredients: Onions, Batter, Oil. Instructions: Slice onions, dip in batter, deep fry until golden.",
    "milkshake": "Ingredients: Ice Cream, Milk, Flavoring. Instructions: Blend ice cream with milk and flavor until smooth.",
    "quesadilla": "Ingredients: Tortillas, Cheese, Chicken or Vegetables. Instructions: Fill tortillas with cheese and filling, grill until cheese melts.",
    "poutine": "Ingredients: French Fries, Cheese Curds, Gravy. Instructions: Top fries with cheese curds, pour hot gravy over.",
    "calzone": "Ingredients: Pizza Dough, Cheese, Meat, Sauce. Instructions: Fill dough with cheese and filling, fold and bake until golden.",
    "quinoa pulao": "Ingredients: Quinoa, Mixed Vegetables, Spices. Instructions: Cook quinoa with vegetables and spices until fluffy.",
    "moong dal": "Ingredients: Moong Lentils, Turmeric, Ginger, Garlic. Instructions: Boil lentils with spices until tender, temper with garlic.",
    "chickpea salad": "Ingredients: Chickpeas, Cucumbers, Tomatoes, Lemon Juice. Instructions: Toss chickpeas with chopped vegetables and lemon dressing.",
    "palak dal": "Ingredients: Spinach, Lentils, Spices. Instructions: Cook lentils and spinach together with spices, serve hot.",
    "vegetable curry": "Ingredients: Mixed Vegetables, Coconut Milk, Spices. Instructions: Cook vegetables in coconut milk and spices until tender.",
    "idli": "Ingredients: Rice, Urad Dal, Fermentation. Instructions: Soak rice and dal, grind into batter, steam in molds.",
    "dosa": "Ingredients: Rice, Urad Dal, Fermentation. Instructions: Soak ingredients, blend into batter, cook thin pancakes on a skillet.",
    "kitchari": "Ingredients: Rice, Moong Dal, Spices. Instructions: Cook rice and dal together with spices and vegetables.",
    "besan cheela": "Ingredients: Chickpea Flour, Vegetables, Spices. Instructions: Mix flour with water and vegetables, cook on a skillet.",
    "fruit chaat": "Ingredients: Mixed Fruits, Chaat Masala, Lemon Juice. Instructions: Toss fruits with chaat masala and lemon juice.",
    "pav bhaji": "Ingredients: Mixed Vegetables, Pav, Spices, Butter. Instructions: Mash cooked vegetables with spices, serve with buttered pav.",
    "vada pav": "Ingredients: Potato, Spices, Pav, Chutney. Instructions: Make a spiced potato filling, fry in batter, serve in a bun with chutney.",
    "bhel puri": "Ingredients: Puffed Rice, Vegetables, Chutney, Sev. Instructions: Mix puffed rice with chopped veggies and chutneys, top with sev.",
    "pani puri": "Ingredients: Semolina Puris, Spiced Water, Potatoes, Chickpeas. Instructions: Fill puris with spiced water and fillings, serve immediately.",
    "dahi puri": "Ingredients: Semolina Puris, Yogurt, Potatoes, Chutneys. Instructions: Fill puris with yogurt and toppings, drizzle with chutneys.",
    "kathi roll": "Ingredients: Roti, Chicken or Paneer, Vegetables, Sauce. Instructions: Fill roti with cooked filling, roll and serve.",
    "chole bhature": "Ingredients: Chickpeas, Flour, Spices, Yogurt. Instructions: Cook chickpeas with spices, serve with deep-fried bhature.",
    "pav sandwich": "Ingredients: Bread, Vegetables, Butter, Chutney. Instructions: Layer vegetables and chutney between bread slices, grill or toast.",
    "egg roll": "Ingredients: Roti, Egg, Onion, Spices. Instructions: Scramble egg with onions and spices, fill in roti and roll.",
    "biryani": "Ingredients: Basmati Rice, Meat or Vegetables, Spices. Instructions: Layer marinated meat or vegetables with rice, cook until done.",
    "momos": "Ingredients: All-purpose Flour, Vegetables or Chicken, Spices. Instructions: Fill dough wrappers with filling, steam until cooked.",
    "thukpa": "Ingredients: Noodles, Vegetables, Broth, Spices. Instructions: Cook noodles in broth with vegetables and spices.",
    "sha phaley": "Ingredients: Flour, Vegetables or Meat, Spices. Instructions: Make dough, fill with spiced filling, fry until golden.",
    "khar": "Ingredients: Raw Papaya, Alkali, Spices. Instructions: Cook papaya with alkali and spices to create a unique dish.",
    "chowmein": "Ingredients: Noodles, Vegetables, Soy Sauce, Spices. Instructions: Stir-fry noodles with mixed vegetables and sauce.",
    "pitha": "Ingredients: Rice Flour, Filling (like jaggery or vegetables). Instructions: Make dumplings with filling and steam or boil.",
    "bhel puri": "Ingredients: Puffed Rice, Vegetables, Chutney. Instructions: Mix puffed rice with chopped veggies and chutneys, serve immediately.",
    "aloo parantha": "Ingredients: Whole Wheat Flour, Potatoes, Spices. Instructions: Stuff dough with spiced potatoes, roll out, and cook on a skillet.",
    "ginger tea": "Ingredients: Tea Leaves, Ginger, Sugar, Milk. Instructions: Boil tea leaves with ginger, add milk and sugar to taste.",
    "kathi roll": "Ingredients: Roti, Vegetables or Meat, Spices. Instructions: Fill roti with cooked filling, roll, and serve.",
    "dal baati churma": "Ingredients: Wheat Flour, Lentils, Ghee, Jaggery. Instructions: Prepare baati by baking dough balls, serve with lentils and churma.",
    "gatte ki sabzi": "Ingredients: Gram Flour, Yogurt, Spices. Instructions: Make dumplings from gram flour, cook in yogurt gravy.",
    "ker sangri": "Ingredients: Ker, Sangri, Spices. Instructions: Soak and cook ker and sangri with spices until tender.",
    "bikaneri bhujia": "Ingredients: Gram Flour, Spices, Oil. Instructions: Prepare dough, shape into thin strands, deep fry until crispy.",
    "laal maas": "Ingredients: Mutton, Red Chillies, Spices. Instructions: Cook mutton with a rich red chili gravy until tender.",
    "paneer gatte": "Ingredients: Paneer, Gram Flour, Spices. Instructions: Make dumplings from paneer, cook in spicy gravy.",
    "pyaaz kachori": "Ingredients: Flour, Spiced Onion Filling. Instructions: Make dough, fill with onion mixture, deep fry until golden.",
    "rajma": "Ingredients: Kidney Beans, Tomatoes, Spices. Instructions: Cook kidney beans in tomato gravy until tender.",
    "methi thepla": "Ingredients: Whole Wheat Flour, Fenugreek Leaves, Spices. Instructions: Make dough with fenugreek, roll out and cook on a skillet.",
    "rabri": "Ingredients: Milk, Sugar, Cardamom. Instructions: Boil milk until thick, add sugar and cardamom, serve chilled.",
    "palak paneer": "Ingredients: Spinach, Paneer, Cream, Spices. Instructions: Cook spinach, blend, and simmer with paneer and spices.",
    "paneer butter masala": "Ingredients: Paneer, Butter, Cream, Tomato Puree, Spices. Instructions: Cook paneer in rich tomato gravy with butter and cream.",
    "shahi paneer": "Ingredients: Paneer, Cashews, Cream, Spices. Instructions: Make a creamy sauce with cashews, add paneer, and simmer.",
    "methi malai paneer": "Ingredients: Fenugreek Leaves, Paneer, Cream, Spices. Instructions: Cook fenugreek and simmer with paneer and cream.",
    "kadai paneer": "Ingredients: Paneer, Bell Peppers, Onions, Spices. Instructions: Stir-fry paneer and vegetables in a spicy tomato gravy.",
    "paneer tikka masala": "Ingredients: Paneer, Yogurt, Spices, Tomato Gravy. Instructions: Marinate paneer, grill, and serve in spicy gravy.",
    "paneer bhurji": "Ingredients: Crumbled Paneer, Onions, Tomatoes, Spices. Instructions: Sauté onions and tomatoes, add crumbled paneer, and cook.",
    "palak paneer": "Ingredients: Spinach, Paneer, Cream, Spices. Instructions: Cook spinach, blend, and simmer with paneer and spices.",
    "chili paneer": "Ingredients: Paneer, Bell Peppers, Soy Sauce, Spices. Instructions: Stir-fry paneer and vegetables in a spicy sauce.",
    "paneer masala": "Ingredients: Paneer, Onions, Tomatoes, Spices. Instructions: Cook paneer in spiced onion-tomato gravy.",
    "idli": "Ingredients: Rice, Urad Dal, Fermentation. Instructions: Soak rice and dal, grind into batter, steam in molds.",
    "dosa": "Ingredients: Rice, Urad Dal, Fermentation. Instructions: Soak ingredients, blend into batter, cook thin pancakes on a skillet.",
    "sambar": "Ingredients: Lentils, Vegetables, Tamarind, Spices. Instructions: Cook lentils and vegetables with tamarind and spices.",
    "rasam": "Ingredients: Tamarind, Tomatoes, Spices, Lentils. Instructions: Cook tamarind and tomatoes with spices, serve as a soup.",
    "upma": "Ingredients: Semolina, Vegetables, Spices. Instructions: Roast semolina, sauté with vegetables, and cook with water.",
    "pongal": "Ingredients: Rice, Moong Dal, Spices, Ghee. Instructions: Cook rice and dal together with spices, serve hot.",
    "vadas": "Ingredients: Urad Dal, Spices. Instructions: Soak dal, grind into a batter, shape into donuts, and deep fry.",
    "biryani": "Ingredients: Basmati Rice, Vegetables or Meat, Spices. Instructions: Layer marinated ingredients with rice, cook until done.",
    "chettinad chicken": "Ingredients: Chicken, Spices, Coconut. Instructions: Cook chicken with a mix of spices and coconut until tender.",
    "coconut chutney": "Ingredients: Coconut, Green Chilies, Ginger, Spices. Instructions: Blend coconut with spices and serve as a dip.",
    "chai": "Ingredients: Tea Leaves, Milk, Sugar, Spices. Instructions: Boil water, add tea leaves and spices, then add milk and sugar.",
    "masala chai": "Ingredients: Tea Leaves, Milk, Spices, Sugar. Instructions: Boil water with spices, add tea leaves, then milk and sugar.",
    "filter coffee": "Ingredients: Coffee Powder, Water, Milk, Sugar. Instructions: Brew coffee using a filter, mix with milk and sugar.",
    "lassi": "Ingredients: Yogurt, Water, Sugar, Cardamom. Instructions: Blend yogurt with water and sugar until smooth.",
    "nimbu pani": "Ingredients: Lemon Juice, Water, Sugar, Salt. Instructions: Mix lemon juice with water, sugar, and salt to taste.",
    "aam panna": "Ingredients: Raw Mangoes, Sugar, Spices, Water. Instructions: Boil mangoes, blend with sugar and spices, dilute with water.",
    "buttermilk": "Ingredients: Yogurt, Water, Spices. Instructions: Blend yogurt with water and spices until smooth.",
    "rose milk": "Ingredients: Milk, Rose Syrup, Sugar. Instructions: Mix milk with rose syrup and sugar to taste.",
    "cold coffee": "Ingredients: Coffee, Milk, Sugar, Ice. Instructions: Brew coffee, blend with milk, sugar, and ice until frothy.",
    "thandai": "Ingredients: Milk, Almonds, Spices, Sugar. Instructions: Soak almonds, blend with milk and spices, serve chilled.",
    "chaas": "Ingredients: Yogurt, Water, Cumin, Salt. Instructions: Blend yogurt with water, add cumin and salt, serve chilled.",
    "kesar badam milk": "Ingredients: Milk, Almonds, Saffron, Sugar. Instructions: Soak almonds, blend with milk, add saffron and sugar.",
    "ganneru": "Ingredients: Rice, Water, Jaggery. Instructions: Cook rice in water, mash, and mix with jaggery for sweetness.",
    "kokum sherbet": "Ingredients: Kokum, Sugar, Water. Instructions: Soak kokum in water, strain, add sugar, and serve chilled.",
    "jaljeera": "Ingredients: Cumin, Mint, Lemon, Water, Salt. Instructions: Blend cumin and mint, mix with water and lemon juice, serve chilled.",
    "sattu drink": "Ingredients: Sattu (roasted gram flour), Water, Lemon, Salt. Instructions: Mix sattu with water, lemon, and salt.",
    "pudina chai": "Ingredients: Tea Leaves, Mint, Milk, Sugar. Instructions: Boil tea with mint, add milk and sugar to taste.",
    "neem ka paani": "Ingredients: Neem Leaves, Water, Lemon. Instructions: Boil neem leaves in water, strain, add lemon juice.",
    "masala lemonade": "Ingredients: Lemon Juice, Black Salt, Mint, Water. Instructions: Mix lemon juice with water, black salt, and mint leaves.",
    "tender coconut water": "Ingredients: Tender Coconut. Instructions: Simply open and enjoy the fresh coconut water.",
    "biryani": "Ingredients: Basmati Rice, Meat or Vegetables, Spices. Instructions: Layer marinated ingredients with rice, cook until done.",
    "paneer tikka": "Ingredients: Paneer, Yogurt, Spices. Instructions: Marinate paneer in yogurt and spices, grill until charred.",
    "pav bhaji": "Ingredients: Mixed Vegetables, Pav, Butter, Spices. Instructions: Mash cooked vegetables with spices, serve with buttered pav.",
    "vada pav": "Ingredients: Potato, Pav, Spices, Chutney. Instructions: Make spiced potato filling, fry in batter, serve in a bun.",
    "bhel puri": "Ingredients: Puffed Rice, Vegetables, Chutneys. Instructions: Mix puffed rice with chopped veggies and chutneys, serve immediately.",
    "pani puri": "Ingredients: Puris, Spiced Water, Potatoes. Instructions: Fill puris with spiced water and fillings, serve immediately.",
    "kathi roll": "Ingredients: Roti, Chicken or Paneer, Vegetables. Instructions: Fill roti with cooked filling, roll and serve.",
    "chole bhature": "Ingredients: Chickpeas, Flour, Spices. Instructions: Cook chickpeas with spices, serve with deep-fried bhature.",
    "dahi puri": "Ingredients: Puris, Yogurt, Chutneys. Instructions: Fill puris with yogurt and toppings, drizzle with chutneys.",
    "egg roll": "Ingredients: Roti, Egg, Onion, Spices. Instructions: Scramble egg with onions and spices, fill in roti and roll.",
    "chocolate cake": "Ingredients: Flour, Cocoa Powder, Sugar, Eggs, Butter. Instructions: Mix ingredients, bake at 350°F for 30 minutes.",
    "vanilla cake": "Ingredients: Flour, Sugar, Eggs, Butter, Vanilla Extract. Instructions: Cream butter and sugar, add eggs, then flour, bake.",
    "red velvet cake": "Ingredients: Flour, Cocoa Powder, Sugar, Eggs, Red Food Coloring. Instructions: Mix, bake, frost with cream cheese icing.",
    "carrot cake": "Ingredients: Grated Carrots, Flour, Sugar, Eggs, Cinnamon. Instructions: Mix ingredients, bake, frost with cream cheese icing.",
    "lemon drizzle cake": "Ingredients: Flour, Sugar, Eggs, Butter, Lemon Zest. Instructions: Mix, bake, drizzle with lemon syrup.",
    "black forest cake": "Ingredients: Chocolate Cake, Cherries, Whipped Cream. Instructions: Layer cake with cherries and cream, decorate.",
    "coffee cake": "Ingredients: Flour, Sugar, Coffee, Eggs, Butter. Instructions: Mix ingredients, bake, serve with coffee.",
    "pound cake": "Ingredients: Flour, Sugar, Butter, Eggs, Milk. Instructions: Cream butter and sugar, add eggs, mix in flour, bake.",
    "banana cake": "Ingredients: Ripe Bananas, Flour, Sugar, Eggs, Butter. Instructions: Mash bananas, mix, bake until golden.",
    "funfetti cake": "Ingredients: Flour, Sugar, Eggs, Butter, Sprinkles. Instructions: Mix ingredients, add sprinkles, bake for a festive treat.",
    "dal makhani": "Ingredients: Black Lentils, Butter, Cream, Spices. Instructions: Slow-cook lentils with spices and cream.",
    "paneer butter masala": "Ingredients: Paneer, Butter, Tomato Puree, Cream, Spices. Instructions: Cook paneer in rich butter-tomato gravy.",
    "aloo gobi": "Ingredients: Potatoes, Cauliflower, Spices. Instructions: Cook potatoes and cauliflower with spices until tender.",
    "jeera rice": "Ingredients: Basmati Rice, Cumin, Ghee. Instructions: Cook rice with cumin seeds in ghee.",
    "roti": "Ingredients: Whole Wheat Flour, Water. Instructions: Make dough, roll into flatbreads, and cook on a skillet.",
    "raita": "Ingredients: Yogurt, Cucumber, Spices. Instructions: Mix yogurt with grated cucumber and spices.",
    "chole": "Ingredients: Chickpeas, Onion, Tomato, Spices. Instructions: Cook chickpeas in spiced onion-tomato gravy.",
    "palak paneer": "Ingredients: Spinach, Paneer, Cream, Spices. Instructions: Cook spinach, blend, and simmer with paneer.",
    "pulao": "Ingredients: Basmati Rice, Mixed Vegetables, Spices. Instructions: Cook rice with assorted vegetables and spices.",
    "gajar halwa": "Ingredients: Carrots, Milk, Sugar, Nuts. Instructions: Cook grated carrots in milk, add sugar and nuts.",
    "tomato soup": "Ingredients: Tomatoes, Onion, Garlic, Basil. Instructions: Cook tomatoes, onions, and garlic, blend until smooth.",
    "vegetable soup": "Ingredients: Mixed Vegetables, Vegetable Broth, Herbs. Instructions: Cook vegetables in broth with herbs until tender.",
    "chicken soup": "Ingredients: Chicken, Carrots, Celery, Broth. Instructions: Simmer chicken with vegetables in broth until cooked.",
    "mushroom soup": "Ingredients: Mushrooms, Cream, Garlic, Thyme. Instructions: Sauté mushrooms and garlic, add cream, and blend.",
    "lentil soup": "Ingredients: Lentils, Carrots, Celery, Spices. Instructions: Cook lentils with vegetables and spices until tender.",
    "pumpkin soup": "Ingredients: Pumpkin, Onion, Garlic, Cream. Instructions: Roast pumpkin, blend with sautéed onion and cream.",
    "butternut squash soup": "Ingredients: Butternut Squash, Onion, Ginger, Broth. Instructions: Cook squash and onion, blend with ginger and broth.",
    "split pea soup": "Ingredients: Split Peas, Carrots, Onion, Broth. Instructions: Cook split peas with vegetables in broth until soft.",
    "beetroot soup": "Ingredients: Beetroot, Onion, Garlic, Vegetable Broth. Instructions: Cook beetroot with onion and garlic, blend until smooth.",
    "spicy noodle soup": "Ingredients: Noodles, Broth, Vegetables, Chili Paste. Instructions: Cook noodles in broth with vegetables and chili paste.",
    "gulab jamun": "Ingredients: Khoya, Flour, Sugar, Cardamom. Instructions: Make dough, shape into balls, fry, and soak in sugar syrup.",
    "jalebi": "Ingredients: Flour, Sugar, Yogurt, Saffron. Instructions: Make batter, fry in circular shapes, and dip in sugar syrup.",
    "barfi": "Ingredients: Milk, Sugar, Cardamom, Nuts. Instructions: Cook milk until thick, add sugar and nuts, set and cut into squares.",
    "kheer": "Ingredients: Rice, Milk, Sugar, Cardamom. Instructions: Cook rice in milk, add sugar, and simmer until thick.",
    "rasgulla": "Ingredients: Chhena, Sugar, Cardamom. Instructions: Make small balls of chhena, boil in sugar syrup until spongy.",
    "peda": "Ingredients: Khoya, Sugar, Cardamom, Nuts. Instructions: Cook khoya with sugar, shape into small discs, garnish with nuts.",
    "motichoor laddoo": "Ingredients: Besan, Sugar, Cardamom. Instructions: Make tiny fried balls, mix with sugar syrup, and form laddoos.",
    "soan papdi": "Ingredients: Flour, Sugar, Ghee, Cardamom. Instructions: Cook flour in ghee, add sugar syrup, and pull to create layers.",
    "burfi": "Ingredients: Milk, Sugar, Nuts, Cardamom. Instructions: Cook milk until thick, add sugar and nuts, set and cut into pieces.",
    "chikki": "Ingredients: Peanuts, Jaggery. Instructions: Roast peanuts, melt jaggery, mix, and set until firm.",
    "besan ladoo": "Ingredients: Besan, Ghee, Sugar, Cardamom. Instructions: Roast besan in ghee, mix with sugar, and form laddoos.",
    "kaju katli": "Ingredients: Cashews, Sugar, Ghee. Instructions: Grind cashews to a powder, cook with sugar, roll into thin sheets.",
    "gajar halwa": "Ingredients: Grated Carrots, Milk, Sugar, Nuts. Instructions: Cook grated carrots in milk until thick, add sugar and nuts.",
    "sooji halwa": "Ingredients: Semolina, Ghee, Sugar, Nuts. Instructions: Roast semolina in ghee, add sugar and water, cook until fluffy.",
    "rasmalai": "Ingredients: Chhena, Milk, Sugar, Cardamom. Instructions: Prepare rasgullas, soak in sweetened milk flavored with cardamom.",
    "doodh peda": "Ingredients: Milk Powder, Sugar, Ghee, Cardamom. Instructions: Mix ingredients, shape into discs, and garnish.",
    "thandai": "Ingredients: Milk, Nuts, Spices, Sugar. Instructions: Blend ingredients, chill, and serve cold.",
    "malpua": "Ingredients: Flour, Sugar, Coconut, Milk. Instructions: Make batter, fry pancakes, and soak in sugar syrup.",
    "puran poli": "Ingredients: Flour, Chana Dal, Jaggery, Cardamom. Instructions: Cook dal, mix with jaggery, stuff in flatbreads, and cook.",
    "ladoo": "Ingredients: Various (e.g., coconut, besan, etc.). Instructions: Prepare base, mix with sugar, and form into balls."
};
    

document.getElementById('findRecipeBtn').addEventListener('click', function() {
    const dish = document.getElementById('dishInput').value.toLowerCase();
    const recipeOutput = document.getElementById('recipeOutput');
    
    if (recipes[dish]) {
        recipeOutput.innerHTML = `<h2>Recipe for ${dish.charAt(0).toUpperCase() + dish.slice(1)}:</h2><p>${recipes[dish]}</p>`;
    } else {
        recipeOutput.innerHTML = `<p>Sorry, recipe for "${dish}" not found.</p>`;
    }
});


